#!/bin/bash
# Mint-Y Theme 
# Light green - 9ab87c
# Dark green - 8fa876

# original light version is #9ab87c
# personallightcolour=436b95

# original dark version is #8fa876
# personaldarkcolour=1685a6

# tooltip color
find src -name "*" -type f -exec sed -i 's/fbeaa0/ecff00/g' {}  \;

# Autogenerated changes are below

